export const appLogos = {};

export const appImages = {
  authBg: require('../../assets/images/authbg.png'),
  photography: require('../../assets/images/photography.png'),
  splash: require('../../assets/images/splash.png'),
  diamond: require('../../assets/images/diamond.png'),
  empty: require('../../assets/images/empty.png'),
  minbg: require('../../assets/images/minbg.png'),
  multiuser: require('../../assets/images/multiuser.png'),
  click: require('../../assets/images/click.png'),
  designer: require('../../assets/images/designer.png'),
  illustrator: require('../../assets/images/illustrator.png'),
  photographer: require('../../assets/images/photographer.png'),
  profile: require('../../assets/images/profile.png'),
  videocreator: require('../../assets/images/videocreator.png'),
  tabBg: require('../../assets/images/tabbg.png'),
  user: require('../../assets/images/user.png'),
  user2: require('../../assets/images/user2.png'),
  user3: require('../../assets/images/user3.png'),
  user4: require('../../assets/images/user4.png'),
  user5: require('../../assets/images/user5.png'),
  tick: require('../../assets/images/tick.png'),
  flower: require('../../assets/images/flower.png'),
  setting: require('../../assets/images/setting.png'),
};

export const appIcons = {
  facebook: require('../../assets/icons/facebook.png'),
  facebook2: require('../../assets/icons/facebook2.png'),
  google: require('../../assets/icons/google.png'),
  search: require('../../assets/icons/search.png'),
  send: require('../../assets/icons/send.png'),
  profile: require('../../assets/icons/profile.png'),
  category: require('../../assets/icons/category.png'),
  notification: require('../../assets/icons/notification.png'),
  homeIcon: require('../../assets/icons/home.png'),
  plusIcon: require('../../assets/icons/plus.png'),
  pluscircle: require('../../assets/icons/plus-circle.png'),
  heart: require('../../assets/icons/heart.png'),
  chat: require('../../assets/icons/chat.png'),
  homeoutline: require('../../assets/icons/home-outline.png'),
  notificationoutline: require('../../assets/icons/notification-outline.png'),
  profileoutline: require('../../assets/icons/profile-outline.png'),
  categoryoutline: require('../../assets/icons/category-outline.png'),
  backarrow: require('../../assets/icons/backarrow.png'),
  upload: require('../../assets/icons/upload.png'),
  eyeIcon: require('../../assets/icons/eye.png'),
  editSquare: require('../../assets/icons/editSquare.png'),
  heartfill: require('../../assets/icons/heartfill.png'),
  cross: require('../../assets/icons/cross.png'),
  setting: require('../../assets/icons/setting.png'),
  gallery: require('../../assets/icons/gallery.png'),
  camera: require('../../assets/icons/camera.png'),
  settings: require('../../assets/icons/settings.png'),
  global: require('../../assets/icons/global.png'),
  instagram: require('../../assets/icons/instagram.png'),
  arrow: require('../../assets/icons/arrow.png'),
  logout: require('../../assets/icons/logout.png'),
  heartfil: require('../../assets/icons/heartfil.png'),
  welcome: require('../../assets/icons/welcome.png'),
};

export const appSvgs = {
  // ...svgicons,
};
export const appJSON = {};
